// Generated from gleam_stdlib 1.0 sources: external parameter labels of
// every stdlib fn that has any. Regenerate with the harvest script if the
// stdlib is updated.
pub const STDLIB_LABELS: &[(&str, &str, &[Option<&str>])] = &[
    ("gleam/bit_array", "append", &[Some("to"), Some("suffix")]),
    ("gleam/bit_array", "slice", &[Some("from"), Some("at"), Some("take")]),
    ("gleam/bit_array", "compare", &[None, Some("with")]),
    ("gleam/bool", "guard", &[Some("when"), Some("return"), Some("otherwise")]),
    ("gleam/bool", "lazy_guard", &[Some("when"), Some("return")]),
    ("gleam/bytes_tree", "prepend", &[Some("to"), Some("prefix")]),
    ("gleam/bytes_tree", "append", &[Some("to"), Some("suffix")]),
    ("gleam/bytes_tree", "prepend_tree", &[Some("to"), Some("prefix")]),
    ("gleam/bytes_tree", "append_tree", &[Some("to"), Some("suffix")]),
    ("gleam/bytes_tree", "prepend_string", &[Some("to"), Some("prefix")]),
    ("gleam/bytes_tree", "append_string", &[Some("to"), Some("suffix")]),
    ("gleam/dict", "insert", &[Some("into"), Some("for"), Some("insert")]),
    ("gleam/dict", "map_values", &[Some("in"), Some("with")]),
    ("gleam/dict", "filter", &[Some("in"), Some("keeping")]),
    ("gleam/dict", "take", &[Some("from"), Some("keeping")]),
    ("gleam/dict", "merge", &[Some("into"), Some("from")]),
    ("gleam/dict", "delete", &[Some("from"), Some("delete")]),
    ("gleam/dict", "drop", &[Some("from"), Some("drop")]),
    ("gleam/dict", "upsert", &[Some("in"), Some("update"), Some("with")]),
    ("gleam/dict", "fold", &[Some("over"), Some("from"), Some("with")]),
    ("gleam/dict", "combine", &[None, None, Some("with")]),
    ("gleam/float", "clamp", &[None, Some("min"), Some("max")]),
    ("gleam/float", "compare", &[None, Some("with")]),
    ("gleam/float", "loosely_compare", &[None, Some("with"), Some("tolerating")]),
    ("gleam/float", "loosely_equals", &[None, Some("with"), Some("tolerating")]),
    ("gleam/float", "power", &[None, Some("of")]),
    ("gleam/float", "modulo", &[None, Some("by")]),
    ("gleam/float", "divide", &[None, Some("by")]),
    ("gleam/int", "power", &[None, Some("of")]),
    ("gleam/int", "clamp", &[None, Some("min"), Some("max")]),
    ("gleam/int", "compare", &[None, Some("with")]),
    ("gleam/int", "divide", &[None, Some("by")]),
    ("gleam/int", "remainder", &[None, Some("by")]),
    ("gleam/int", "modulo", &[None, Some("by")]),
    ("gleam/int", "floor_divide", &[None, Some("by")]),
    ("gleam/int", "range", &[Some("from"), Some("to"), Some("with"), Some("run")]),
    ("gleam/list", "length", &[Some("of")]),
    ("gleam/list", "count", &[None, Some("where")]),
    ("gleam/list", "contains", &[None, Some("any")]),
    ("gleam/list", "group", &[None, Some("by")]),
    ("gleam/list", "filter", &[None, Some("keeping")]),
    ("gleam/list", "filter_map", &[None, Some("with"), None]),
    ("gleam/list", "map", &[None, Some("with")]),
    ("gleam/list", "map2", &[None, None, Some("with")]),
    ("gleam/list", "map_fold", &[Some("over"), Some("from"), Some("with"), None]),
    ("gleam/list", "index_map", &[None, Some("with")]),
    ("gleam/list", "try_map", &[Some("over"), Some("with"), None]),
    ("gleam/list", "drop", &[Some("from"), Some("up_to")]),
    ("gleam/list", "take", &[Some("from"), Some("up_to")]),
    ("gleam/list", "prepend", &[Some("to"), Some("this")]),
    ("gleam/list", "flat_map", &[Some("over"), Some("with")]),
    ("gleam/list", "fold", &[Some("over"), Some("from"), Some("with")]),
    ("gleam/list", "fold_right", &[Some("over"), Some("from"), Some("with")]),
    ("gleam/list", "index_fold", &[Some("over"), Some("from"), Some("with")]),
    ("gleam/list", "try_fold", &[Some("over"), Some("from"), Some("with"), None]),
    ("gleam/list", "fold_until", &[Some("over"), Some("from"), Some("with")]),
    ("gleam/list", "find", &[Some("in"), Some("one_that")]),
    ("gleam/list", "find_map", &[Some("in"), Some("with"), None]),
    ("gleam/list", "all", &[Some("in"), Some("satisfying")]),
    ("gleam/list", "any", &[Some("in"), Some("satisfying")]),
    ("gleam/list", "zip", &[None, Some("with")]),
    ("gleam/list", "strict_zip", &[None, Some("with")]),
    ("gleam/list", "intersperse", &[None, Some("with")]),
    ("gleam/list", "sort", &[None, Some("by")]),
    ("gleam/list", "repeat", &[Some("item"), Some("times")]),
    ("gleam/list", "split", &[Some("list"), Some("at")]),
    ("gleam/list", "split_while", &[Some("list"), Some("satisfying")]),
    ("gleam/list", "key_find", &[Some("in"), Some("find")]),
    ("gleam/list", "key_filter", &[Some("in"), Some("find")]),
    ("gleam/list", "try_each", &[Some("over"), Some("with"), None]),
    ("gleam/list", "partition", &[None, Some("with")]),
    ("gleam/list", "window", &[None, Some("by")]),
    ("gleam/list", "drop_while", &[Some("in"), Some("satisfying")]),
    ("gleam/list", "take_while", &[Some("in"), Some("satisfying")]),
    ("gleam/list", "chunk", &[Some("in"), Some("by")]),
    ("gleam/list", "sized_chunk", &[Some("in"), Some("into")]),
    ("gleam/list", "reduce", &[Some("over"), Some("with")]),
    ("gleam/list", "scan", &[Some("over"), Some("from"), Some("with")]),
    ("gleam/list", "combinations", &[None, Some("by")]),
    ("gleam/list", "max", &[Some("over"), Some("with")]),
    ("gleam/list", "sample", &[Some("from"), Some("up_to")]),
    ("gleam/option", "unwrap", &[None, Some("or")]),
    ("gleam/option", "lazy_unwrap", &[None, Some("or")]),
    ("gleam/option", "map", &[Some("over"), Some("with")]),
    ("gleam/option", "then", &[None, Some("apply")]),
    ("gleam/order", "compare", &[None, Some("with")]),
    ("gleam/order", "break_tie", &[Some("in"), Some("with")]),
    ("gleam/order", "lazy_break_tie", &[Some("in"), Some("with")]),
    ("gleam/pair", "map_first", &[Some("of"), Some("with")]),
    ("gleam/pair", "map_second", &[Some("of"), Some("with")]),
    ("gleam/result", "map", &[Some("over"), Some("with")]),
    ("gleam/result", "map_error", &[Some("over"), Some("with")]),
    ("gleam/result", "try", &[None, Some("apply"), None]),
    ("gleam/result", "unwrap", &[None, Some("or")]),
    ("gleam/result", "lazy_unwrap", &[None, Some("or")]),
    ("gleam/result", "unwrap_error", &[None, Some("or")]),
    ("gleam/result", "try_recover", &[None, Some("with"), None]),
    ("gleam/set", "insert", &[Some("into"), Some("this")]),
    ("gleam/set", "contains", &[Some("in"), Some("this")]),
    ("gleam/set", "delete", &[Some("from"), Some("this")]),
    ("gleam/set", "fold", &[Some("over"), Some("from"), Some("with")]),
    ("gleam/set", "filter", &[Some("in"), Some("keeping")]),
    ("gleam/set", "map", &[None, Some("with")]),
    ("gleam/set", "drop", &[Some("from"), Some("drop")]),
    ("gleam/set", "take", &[Some("from"), Some("keeping")]),
    ("gleam/set", "union", &[Some("of"), Some("and")]),
    ("gleam/set", "intersection", &[Some("of"), Some("and")]),
    ("gleam/set", "difference", &[Some("from"), Some("minus")]),
    ("gleam/set", "is_subset", &[None, Some("of")]),
    ("gleam/set", "is_disjoint", &[None, Some("from")]),
    ("gleam/set", "symmetric_difference", &[Some("of"), Some("and")]),
    ("gleam/string", "replace", &[Some("in"), Some("each"), Some("with")]),
    ("gleam/string", "slice", &[Some("from"), Some("at_index"), Some("length")]),
    ("gleam/string", "crop", &[Some("from"), Some("before")]),
    ("gleam/string", "drop_start", &[Some("from"), Some("up_to")]),
    ("gleam/string", "drop_end", &[Some("from"), Some("up_to")]),
    ("gleam/string", "contains", &[Some("does"), Some("contain")]),
    ("gleam/string", "split", &[None, Some("on")]),
    ("gleam/string", "split_once", &[None, Some("on")]),
    ("gleam/string", "append", &[Some("to"), Some("suffix")]),
    ("gleam/string", "repeat", &[None, Some("times")]),
    ("gleam/string", "join", &[None, Some("with")]),
    ("gleam/string", "pad_start", &[None, Some("to"), Some("with")]),
    ("gleam/string", "pad_end", &[None, Some("to"), Some("with")]),
    ("gleam/string", "remove_prefix", &[Some("from"), Some("matching")]),
    ("gleam/string", "remove_suffix", &[Some("from"), Some("matching")]),
    ("gleam/string_tree", "prepend", &[Some("to"), Some("prefix")]),
    ("gleam/string_tree", "append", &[Some("to"), Some("suffix")]),
    ("gleam/string_tree", "prepend_tree", &[Some("to"), Some("prefix")]),
    ("gleam/string_tree", "append_tree", &[Some("to"), Some("suffix")]),
    ("gleam/string_tree", "join", &[None, Some("with")]),
    ("gleam/string_tree", "split", &[None, Some("on")]),
    ("gleam/string_tree", "replace", &[Some("in"), Some("each"), Some("with")]),
];
