[package]
name = "gleam-to-clj"
version = "0.1.0"
edition = "2021"

[dependencies]
gleam-core = { git = "https://github.com/escherize/gleam", rev = "249942830234ae912fceed7e59e0760cc32d3e72" }
camino = "1"
im = "15"
src-span = { git = "https://github.com/escherize/gleam", rev = "249942830234ae912fceed7e59e0760cc32d3e72" }
ecow = "0.3"
vec1 = "1"

[profile.dev]
debug = 0
